modified:   rsc/scripts/globalfuncs

diff --git a/rsc/scripts/globalfuncs b/rsc/scripts/globalfuncs
--- a/rsc/scripts/globalfuncs
+++ b/rsc/scripts/globalfuncs
@@ -166,7 +166,7 @@ function isClusterBusy()
   # does qstat work ?
   qstat &>/dev/null
   if [ $? != 0 ] ; then 
-    echo "ERROR : qstat failed. Is Network available ?" >&2
+    echo "ERROR : qstat failed on $(date). Is Network available ?" >&2
     echo "1"
     return
   fi
