modified:   globalvars  	modified:   rsc/fsl/topup/applytopup_32  	modified:   rsc/fsl/topup/topup_32  	modified:   rsc/scripts/globalfuncs  	modified:   rsc/scripts/globalvars_test  	modified:   rsc/scripts/main.sh

diff --git a/rsc/scripts/globalfuncs b/rsc/scripts/globalfuncs
--- a/rsc/scripts/globalfuncs
+++ b/rsc/scripts/globalfuncs
@@ -72,7 +72,7 @@ function getAquParams()
   local param=""
   local line=""
   
-  if [ ! -f $conftxt ] ; then echo "defineBOLDparams(): ERROR: info file '$conftxt' not found. You will need to create that file..." >&2 ; exit 1 ; fi
+  if [ ! -f $conftxt ] ; then echo "getAquParams(): ERROR: info file '$conftxt' not found. You will need to create that file..." >&2 ; exit 1 ; fi
   
   if [ "$3" = "" ] ; then
   
